apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 3
  selector:
    matchLabels: {app: postgres}
  template:
    metadata:
      labels: {app: postgres}
    spec:
      containers:
        - name: postgres
          image: public.ecr.aws/docker/library/postgres:15-alpine
          command: ["bash", "/scripts/Q2.sh"]
          ports: [{containerPort: 5432, name: postgres}]
          env:
            - name: POSTGRES_PASSWORD
              value: "postgres_pw"
            - name: REPLICA_USR
              value: "replica_usr" 
            - name: REPLICA_PW
              value: "replica_pw"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "md5"
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: script-config
              mountPath: /scripts
      volumes:
        - name: script-config
          configMap:
            name: postgres-config
            defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
