#ifndef __GROVE_MAP__H
#define __GROVE_MAP__H

#define ADC_MIN_PIN			26
#define ADC_SENSOR_SOUND_NUM		0 // Analog port
#define ADC_SENSOR_SOUND_PIN 		(ADC_MIN_PIN + ADC_SENSOR_SOUND_NUM)
#define ADC_SENSOR_SOUND_VREF 		3.3
#define ADC_SENSOR_SOUND_RANGE 		(1<<12)
#define ADC_SENSOR_SOUND_CONVERT	(ADC_SENSOR_SOUND_VREF / (ADC_SENSOR_SOUND_RANGE-1))
#define ADC_SENSOR_LIGHT_NUM		1
#define ADC_SENSOR_LIGHT_PIN		(ADC_MIN_PIN + ADC_SENSOR_LIGHT_NUM)

#endif
